spring:
    datasource:
        platform: mariadb
        driverClassName: org.mariadb.jdbc.Driver
        # Fixed in v1.3.3. Doesn't work with mariadb-connector-j v1.3.2 (CONJ-227)
        url: jdbc:mariadb:failover://192.168.33.11:3306/test?autoReconnect=true
        # If some of the hosts is down, app won't launch. v1.3.3
        #url: jdbc:mariadb:failover://192.168.33.11:3306,192.168.33.12:3306,192.168.33.13:3306/test?autoReconnect=true
        # Works with mariadb-connector-j v1.3.2
        #url: jdbc:mysql:failover://192.168.33.11:3306/test
        username: root
        password: test

        timeBetweenEvictionRunsMillis: 1000
        testWhileIdle: true
        validationQuery: SELECT 1
    jpa:
        ddl-auto: ''
